name: iOS starter workflow

on:
  workflow_dispatch:
  
env:
  LANG: "en_US.UTF-8" 
  LC_ALL: "en_US.UTF-8"

jobs:
  build:
    name: Build and Test iOS App
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Setup ruby env
        uses: ruby/setup-ruby@v1.139.0
        with:
          ruby-version: '3.2.1'
        env:
          ImageOS: 'macos12'

      - name: Install Fastlane
        run: bundle install
            
      - name: Install & update Fastlane plugins
        run: |
          bundle exec fastlane install_plugins
          bundle exec fastlane update_plugins

      - name: Build app
        run: bundle exec fastlane ios build_test_app

      - name: Run tests
        run: bundle exec fastlane ios tests

      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: ./Build/SimpleCalculator.xcresult
